"""Reusable analysis and data-quality code for the QL2 Sixt Canada rate feed."""

from ql2_sixt_canada_analysis.comparison import (
    INVALID_OFFER_SAMPLE_LIMIT,
    BaselineEvidence,
    InvalidOfferSample,
    OfferDefect,
    OfferSignature,
    OfferStreamRole,
    offer_signature,
    ComparisonPreconditionError,
    DuplicateInferenceBlocker,
    IdentityEvidence,
    LocationAliasNotConfirmedError,
    LocationStreamComparisonReport,
    LocationStreamComparisonStatus,
    OfferSetResult,
    ScopeBaseline,
    TemporalOverlap,
    canonical_location_keys,
    compare_location_streams,
    validate_confirmed_location_alias,
)
from ql2_sixt_canada_analysis.coverage import (
    location_pair_evidence,
    LocationCoverageError,
    LocationCoverageReport,
    assess_dataset_location_coverage,
    assess_expected_location_coverage,
    validate_expected_location_coverage,
)
from ql2_sixt_canada_analysis.identifiers import (
    IdentifierDtypeError,
    IdentifierTypeConflictError,
    MissingIdentifierColumnError,
    cast_identifier_fields,
    cast_identifiers_for_raw_datasets,
    validate_identifier_dtypes,
    validate_raw_dataset_identifier_dtypes,
)
from ql2_sixt_canada_analysis.ingestion import (
    SAFE_ON_BAD_LINES,
    IncompleteSourceOptionError,
    RawDatasetPaths,
    RawDatasets,
    discover_raw_csvs,
    load_raw_datasets,
)
from ql2_sixt_canada_analysis.quality import (
    BlankRowResult,
    RawDatasetBlankRowResults,
    remove_blank_rows_from_raw_datasets,
    remove_completely_blank_rows,
)
from ql2_sixt_canada_analysis.reconciliation import (
    DeclaredCountFieldReport,
    job_detail_count_results,
    JobDetailReconciliationError,
    JobDetailReconciliationReport,
    ReconciliationPreconditionError,
    assess_job_detail_reconciliation,
    validate_job_detail_reconciliation,
)
from ql2_sixt_canada_analysis.relationships import (
    OneToManyJoinReport,
    OneToManyRelationshipError,
    RelationshipPreconditionError,
    ValidatedJoinError,
    ValidatedJoinResult,
    assess_one_to_many_join,
    join_jobs_to_details,
    validate_one_to_many_join,
)
from ql2_sixt_canada_analysis.schemas import (
    PROJECT_DEFAULT,
    SOURCE_STREAM_COVERAGE_TEMPLATE,
    project_default,
    ANALYSIS_CARS_DEFINITION,
    ANALYSIS_DATASET_DEFINITIONS,
    ANALYSIS_JOBS_DEFINITION,
    ANALYSIS_JOB_DETAIL_RELATIONSHIP,
    ANALYSIS_TEMPORAL_RECONCILIATION,
    CONFIDENTIAL_TECHNICAL_COLUMNS,
    JOB_LINKAGE_KEY_COLUMN,
    OFFER_POSITION_KEY_COLUMN,
    OFFER_POSITION_KEY_DTYPE,
    SOURCE_JOB_IDENTIFIER_COLUMN,
    SOURCE_OFFER_POSITION_COLUMN,
    COLLECTION_SCHEDULE,
    DATASET_DEFINITIONS,
    IDENTIFIER_DTYPE,
    INVESTIGATED_LOCATION_STREAM,
    MINIMUM_DUPLICATE_PAIRED_CAPTURES,
    LocationIdentityPolicy,
    LocationPolicyAuthority,
    LocationPolicyConfigurationError,
    LocationPolicyScope,
    LocationPolicyScopeDefect,
    LocationPolicyState,
    assess_location_policy_scope,
    VEHICLE_ATTRIBUTE_STABILITY,
    AttributeComparisonPolicy,
    MissingValueStabilityPolicy,
    VehicleAttributeDefinition,
    VehicleStabilityConfigurationError,
    VehicleStabilityDefinition,
    COMPARED_LOCATION_STREAMS,
    CapturePairing,
    LocationStreamComparisonDefinition,
    CollectionScheduleDefinition,
    JOB_DETAIL_RELATIONSHIP,
    SHARED_IDENTIFIER_COLUMNS,
    DatasetDefinition,
    DatasetKey,
    JobDetailRelationshipDefinition,
    KeyConfigurationError,
    LocationCoverageConfigurationError,
    LocationCoverageDefinition,
    LocationCoverageMode,
    RelationshipConfigurationError,
    TEMPORAL_RECONCILIATION,
    ReportingDateRule,
    TemporalAwareness,
    TemporalConfigurationError,
    TemporalDateCheck,
    TemporalFieldDefinition,
    TemporalKind,
    TemporalReconciliationDefinition,
    TemporalReplicationRule,
    TimestampOrderingRule,
    get_dataset_definition,
)
from ql2_sixt_canada_analysis.streams import (
    CollectionScheduleAssessment,
    CollectionScheduleStatus,
    ScheduledCoverageBlocker,
    ScheduledCoverageReport,
    StreamTimeCoverage,
    assess_collection_schedule,
    assess_scheduled_time_coverage,
    ExpectedLocationStreamsReport,
    ExpectedStreamBlocker,
    ExpectedStreamResult,
    assess_expected_location_streams,
    StreamEventAccounting,
    LocationStreamError,
    LocationStreamInvestigationReport,
    LocationStreamStatus,
    PipelineStage,
    StreamContinuity,
    TimeCoverageStatus,
    investigate_location_stream,
    resolve_expected_location,
    validate_location_stream,
)
from ql2_sixt_canada_analysis.city_integrity import (
    CITY_INTEGRITY_SAMPLE_LIMIT,
    CityIntegrityBlocker,
    CityIntegrityError,
    CityIntegrityReport,
    ScopeMismatchSample,
    assess_city_integrity,
    unassignable_scope_mask,
    validate_city_integrity,
)
from ql2_sixt_canada_analysis.join_readiness import (
    JobDetailJoinBlocker,
    JobDetailJoinReadiness,
    UntrustedJoinError,
    assess_job_detail_join_readiness,
    require_trusted_job_detail_join,
)
from ql2_sixt_canada_analysis.readiness import (
    CompletenessBlocker,
    CompletenessReport,
    assess_completeness,
    AnalyticalLocationKeys,
    LocationPolicyReport,
    PricingBlocker,
    PricingNotReadyError,
    PricingReadinessReport,
    apply_location_policy,
    assess_location_policy,
    assess_pricing_readiness,
    validate_pricing_readiness,
)
from ql2_sixt_canada_analysis.stability import (
    VehicleAttributeStabilityError,
    VehicleAttributeStabilityReport,
    VehicleStabilityPreconditionError,
    VehicleStabilityReport,
    VehicleEntityHistory,
    VehicleStabilityStatus,
    assess_vehicle_attribute_stability,
    classify_vehicle_entities,
    validate_vehicle_attribute_stability,
)
from ql2_sixt_canada_analysis.temporal import (
    RuleStatus,
    TemporalFieldReport,
    TemporalParseError,
    TemporalParseResult,
    TemporalPreconditionError,
    TemporalReconciliationError,
    TemporalReconciliationReport,
    TemporalRuleReport,
    assess_temporal_reconciliation,
    parse_temporal_field,
    validate_temporal_reconciliation,
)
from ql2_sixt_canada_analysis.unique_keys import (
    RawDatasetUniqueKeyReports,
    UniqueKeyReport,
    UniqueKeyViolationError,
    assess_raw_dataset_unique_keys,
    assess_unique_key,
    validate_raw_dataset_unique_keys,
    validate_unique_key,
)

__all__ = [
    "ANALYSIS_CARS_DEFINITION",
    "ANALYSIS_DATASET_DEFINITIONS",
    "ANALYSIS_JOBS_DEFINITION",
    "ANALYSIS_JOB_DETAIL_RELATIONSHIP",
    "ANALYSIS_LOCATION_STREAM_COMPARISON",
    "ANALYSIS_TEMPORAL_RECONCILIATION",
    "CONFIDENTIAL_TECHNICAL_COLUMNS",
    "JOB_LINKAGE_KEY_COLUMN",
    "OFFER_POSITION_KEY_COLUMN",
    "OFFER_POSITION_KEY_DTYPE",
    "SOURCE_JOB_IDENTIFIER_COLUMN",
    "SOURCE_OFFER_POSITION_COLUMN",
    "JobLinkageBlocker",
    "JobLinkageNotReadyError",
    "JobLinkagePolicy",
    "JobLinkagePolicyError",
    "JobLinkagePolicyStatus",
    "JobLinkagePreconditionError",
    "JobLinkageReport",
    "JobLinkageResult",
    "assess_job_linkage",
    "job_linkage_policy_from_record",
    "load_job_linkage_policy",
    "require_job_linkage",
    "CollectionScheduleAssessment",
    "CollectionScheduleStatus",
    "ScheduledCoverageBlocker",
    "ScheduledCoverageReport",
    "StreamTimeCoverage",
    "assess_collection_schedule",
    "assess_scheduled_time_coverage",
    "INVALID_OFFER_SAMPLE_LIMIT",
    "BaselineEvidence",
    "InvalidOfferSample",
    "OfferDefect",
    "OfferSignature",
    "OfferStreamRole",
    "offer_signature",
    "CITY_INTEGRITY_SAMPLE_LIMIT",
    "CityIntegrityBlocker",
    "CityIntegrityError",
    "CityIntegrityReport",
    "ScopeMismatchSample",
    "assess_city_integrity",
    "unassignable_scope_mask",
    "validate_city_integrity",
    "ExpectedLocationStreamsReport",
    "ExpectedStreamBlocker",
    "ExpectedStreamResult",
    "assess_expected_location_streams",
    "SAFE_ON_BAD_LINES",
    "IncompleteSourceOptionError",
    "location_pair_evidence",
    "DeclaredCountFieldReport",
    "job_detail_count_results",
    "StreamEventAccounting",
    "CompletenessBlocker",
    "CompletenessReport",
    "assess_completeness",
    "DuplicateInferenceBlocker",
    "MINIMUM_DUPLICATE_PAIRED_CAPTURES",
    "VehicleEntityHistory",
    "classify_vehicle_entities",
    "JobDetailJoinBlocker",
    "JobDetailJoinReadiness",
    "UntrustedJoinError",
    "assess_job_detail_join_readiness",
    "require_trusted_job_detail_join",
    "VANCOUVER_LOCATION_POLICY",
    "LocationIdentityPolicy",
    "LocationPolicyAuthority",
    "LocationPolicyConfigurationError",
    "LocationPolicyScope",
    "LocationPolicyScopeDefect",
    "LocationPolicyState",
    "assess_location_policy_scope",
    "AnalyticalLocationKeys",
    "LocationPolicyReport",
    "PricingBlocker",
    "PricingNotReadyError",
    "PricingReadinessReport",
    "apply_location_policy",
    "assess_location_policy",
    "assess_pricing_readiness",
    "validate_pricing_readiness",
    "VEHICLE_ATTRIBUTE_STABILITY",
    "AttributeComparisonPolicy",
    "MissingValueStabilityPolicy",
    "VehicleAttributeDefinition",
    "VehicleStabilityConfigurationError",
    "VehicleStabilityDefinition",
    "VehicleAttributeStabilityError",
    "VehicleAttributeStabilityReport",
    "VehicleStabilityPreconditionError",
    "VehicleStabilityReport",
    "VehicleStabilityStatus",
    "assess_vehicle_attribute_stability",
    "validate_vehicle_attribute_stability",
    "COMPARED_LOCATION_STREAMS",
    "LOCATION_STREAM_COMPARISON",
    "CapturePairing",
    "LocationStreamComparisonDefinition",
    "ComparisonPreconditionError",
    "IdentityEvidence",
    "LocationAliasNotConfirmedError",
    "LocationStreamComparisonReport",
    "LocationStreamComparisonStatus",
    "OfferSetResult",
    "ScopeBaseline",
    "TemporalOverlap",
    "canonical_location_keys",
    "compare_location_streams",
    "validate_confirmed_location_alias",
    "COLLECTION_SCHEDULE",
    "ReportingDateRule",
    "RuleStatus",
    "TEMPORAL_RECONCILIATION",
    "TemporalAwareness",
    "TemporalConfigurationError",
    "TemporalDateCheck",
    "TemporalFieldDefinition",
    "TemporalFieldReport",
    "TemporalKind",
    "TemporalParseError",
    "TemporalParseResult",
    "TemporalPreconditionError",
    "TemporalReconciliationDefinition",
    "TemporalReconciliationError",
    "TemporalReconciliationReport",
    "TemporalReplicationRule",
    "TemporalRuleReport",
    "TimestampOrderingRule",
    "assess_temporal_reconciliation",
    "parse_temporal_field",
    "validate_temporal_reconciliation",
    "CollectionScheduleDefinition",
    "DATASET_DEFINITIONS",
    "INVESTIGATED_LOCATION_STREAM",
    "LocationStreamError",
    "LocationStreamInvestigationReport",
    "LocationStreamStatus",
    "PipelineStage",
    "StreamContinuity",
    "TimeCoverageStatus",
    "assess_dataset_location_coverage",
    "investigate_location_stream",
    "resolve_expected_location",
    "validate_location_stream",
    "BlankRowResult",
    "DatasetDefinition",
    "DatasetKey",
    "EXPECTED_LOCATION_COVERAGE",
    "IDENTIFIER_DTYPE",
    "IdentifierDtypeError",
    "IdentifierTypeConflictError",
    "JOB_DETAIL_RELATIONSHIP",
    "JobDetailReconciliationError",
    "JobDetailReconciliationReport",
    "JobDetailRelationshipDefinition",
    "KeyConfigurationError",
    "LocationCoverageConfigurationError",
    "LocationCoverageDefinition",
    "LocationCoverageError",
    "LocationCoverageMode",
    "LocationCoverageReport",
    "OneToManyJoinReport",
    "OneToManyRelationshipError",
    "MissingIdentifierColumnError",
    "SHARED_IDENTIFIER_COLUMNS",
    "RawDatasetBlankRowResults",
    "RawDatasetPaths",
    "ReconciliationPreconditionError",
    "RelationshipConfigurationError",
    "RelationshipPreconditionError",
    "RawDatasetUniqueKeyReports",
    "RawDatasets",
    "UniqueKeyReport",
    "UniqueKeyViolationError",
    "ValidatedJoinError",
    "ValidatedJoinResult",
    "assess_expected_location_coverage",
    "assess_job_detail_reconciliation",
    "assess_one_to_many_join",
    "assess_raw_dataset_unique_keys",
    "assess_unique_key",
    "cast_identifier_fields",
    "cast_identifiers_for_raw_datasets",
    "discover_raw_csvs",
    "get_dataset_definition",
    "PROJECT_DEFAULT",
    "SOURCE_STREAM_COVERAGE_TEMPLATE",
    "project_default",
    "EXPECTED_STREAM_DECISIONS",
    "ExpectedStreamAuthorityStatus",
    "ExpectedStreamContract",
    "ExpectedStreamContractBlocker",
    "current_expected_stream_contract",
    "expected_stream_contract_from_record",
    "resolve_expected_stream_contract",
    "load_current_decision_record",
    "join_jobs_to_details",
    "load_raw_datasets",
    "remove_blank_rows_from_raw_datasets",
    "remove_completely_blank_rows",
    "validate_identifier_dtypes",
    "validate_expected_location_coverage",
    "validate_job_detail_reconciliation",
    "validate_one_to_many_join",
    "validate_raw_dataset_identifier_dtypes",
    "validate_raw_dataset_unique_keys",
    "validate_unique_key",
]


#: Names served lazily from :mod:`ql2_sixt_canada_analysis.job_linkage`, which
#: depends on the authority-record module; loading it on first use keeps
#: ``python -m ql2_sixt_canada_analysis.authority_decisions`` free of a re-import.
_LAZY_JOB_LINKAGE = frozenset({
    "JobLinkageBlocker",
    "JobLinkageNotReadyError",
    "JobLinkagePolicy",
    "JobLinkagePolicyError",
    "JobLinkagePolicyStatus",
    "JobLinkagePreconditionError",
    "JobLinkageReport",
    "JobLinkageResult",
    "assess_job_linkage",
    "job_linkage_policy_from_record",
    "load_job_linkage_policy",
    "require_job_linkage",
})


#: The authority-resolved contract and the definitions built on it (resolved
#: on first access from :mod:`ql2_sixt_canada_analysis.schemas`).
_LAZY_SCHEMAS = frozenset({"ANALYSIS_LOCATION_STREAM_COMPARISON", "EXPECTED_LOCATION_COVERAGE",
                           "LOCATION_STREAM_COMPARISON", "VANCOUVER_LOCATION_POLICY"})

#: Names served lazily from :mod:`ql2_sixt_canada_analysis.expected_stream_contract`
#: and :mod:`ql2_sixt_canada_analysis.authority_decisions`.
_LAZY_OTHER = {
    "EXPECTED_STREAM_DECISIONS": "expected_stream_contract",
    "ExpectedStreamAuthorityStatus": "expected_stream_contract",
    "ExpectedStreamContract": "expected_stream_contract",
    "ExpectedStreamContractBlocker": "expected_stream_contract",
    "current_expected_stream_contract": "expected_stream_contract",
    "expected_stream_contract_from_record": "expected_stream_contract",
    "resolve_expected_stream_contract": "expected_stream_contract",
    "load_current_decision_record": "authority_decisions",
}


def __getattr__(name: str):  # type: ignore[no-untyped-def]  # PEP 562
    if name in _LAZY_SCHEMAS:
        from ql2_sixt_canada_analysis import schemas

        return getattr(schemas, name)
    if name in _LAZY_OTHER:
        import importlib

        return getattr(importlib.import_module(f"ql2_sixt_canada_analysis.{_LAZY_OTHER[name]}"), name)
    if name in _LAZY_JOB_LINKAGE:
        from ql2_sixt_canada_analysis import job_linkage

        return getattr(job_linkage, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
