"""Reusable analysis and data-quality code for the QL2 Sixt Canada rate feed."""

from ql2_sixt_canada_analysis.comparison import (
    INVALID_OFFER_SAMPLE_LIMIT,
    BaselineEvidence,
    InvalidOfferSample,
    OfferDefect,
    OfferSignature,
    OfferStreamRole,
    offer_signature,
    ComparisonPreconditionError,
    DuplicateInferenceBlocker,
    IdentityEvidence,
    LocationAliasNotConfirmedError,
    LocationStreamComparisonReport,
    LocationStreamComparisonStatus,
    OfferSetResult,
    ScopeBaseline,
    TemporalOverlap,
    canonical_location_keys,
    compare_location_streams,
    validate_confirmed_location_alias,
)
from ql2_sixt_canada_analysis.coverage import (
    location_pair_evidence,
    LocationCoverageError,
    LocationCoverageReport,
    assess_dataset_location_coverage,
    assess_expected_location_coverage,
    validate_expected_location_coverage,
)
from ql2_sixt_canada_analysis.identifiers import (
    IdentifierDtypeError,
    IdentifierTypeConflictError,
    MissingIdentifierColumnError,
    cast_identifier_fields,
    cast_identifiers_for_raw_datasets,
    validate_identifier_dtypes,
    validate_raw_dataset_identifier_dtypes,
)
from ql2_sixt_canada_analysis.ingestion import (
    SAFE_ON_BAD_LINES,
    IncompleteSourceOptionError,
    RawDatasetPaths,
    RawDatasets,
    discover_raw_csvs,
    load_raw_datasets,
)
from ql2_sixt_canada_analysis.quality import (
    BlankRowResult,
    RawDatasetBlankRowResults,
    remove_blank_rows_from_raw_datasets,
    remove_completely_blank_rows,
)
from ql2_sixt_canada_analysis.reconciliation import (
    DeclaredCountFieldReport,
    job_detail_count_results,
    JobDetailReconciliationError,
    JobDetailReconciliationReport,
    ReconciliationPreconditionError,
    assess_job_detail_reconciliation,
    validate_job_detail_reconciliation,
)
from ql2_sixt_canada_analysis.relationships import (
    OneToManyJoinReport,
    OneToManyRelationshipError,
    RelationshipPreconditionError,
    ValidatedJoinError,
    ValidatedJoinResult,
    assess_one_to_many_join,
    join_jobs_to_details,
    validate_one_to_many_join,
)
from ql2_sixt_canada_analysis.schemas import (
    PROJECT_DEFAULT,
    SOURCE_STREAM_COVERAGE_TEMPLATE,
    project_default,
    ANALYSIS_CARS_DEFINITION,
    ANALYSIS_DATASET_DEFINITIONS,
    ANALYSIS_JOBS_DEFINITION,
    ANALYSIS_JOB_DETAIL_RELATIONSHIP,
    ANALYSIS_TEMPORAL_RECONCILIATION,
    CONFIDENTIAL_TECHNICAL_COLUMNS,
    JOB_LINKAGE_KEY_COLUMN,
    OFFER_POSITION_KEY_COLUMN,
    OFFER_POSITION_KEY_DTYPE,
    SOURCE_JOB_IDENTIFIER_COLUMN,
    SOURCE_OFFER_POSITION_COLUMN,
    COLLECTION_SCHEDULE,
    DATASET_DEFINITIONS,
    IDENTIFIER_DTYPE,
    INVESTIGATED_LOCATION_STREAM,
    MINIMUM_DUPLICATE_PAIRED_CAPTURES,
    LocationIdentityPolicy,
    LocationPolicyAuthority,
    LocationPolicyConfigurationError,
    LocationPolicyScope,
    LocationPolicyScopeDefect,
    LocationPolicyState,
    assess_location_policy_scope,
    VEHICLE_ATTRIBUTE_STABILITY,
    AttributeComparisonPolicy,
    MissingValueStabilityPolicy,
    VehicleAttributeDefinition,
    VehicleStabilityConfigurationError,
    VehicleStabilityDefinition,
    COMPARED_LOCATION_STREAMS,
    CapturePairing,
    LocationStreamComparisonDefinition,
    CollectionScheduleDefinition,
    JOB_DETAIL_RELATIONSHIP,
    SHARED_IDENTIFIER_COLUMNS,
    DatasetDefinition,
    DatasetKey,
    JobDetailRelationshipDefinition,
    KeyConfigurationError,
    LocationCoverageConfigurationError,
    LocationCoverageDefinition,
    LocationCoverageMode,
    RelationshipConfigurationError,
    TEMPORAL_RECONCILIATION,
    ReportingDateRule,
    TemporalAwareness,
    TemporalConfigurationError,
    TemporalDateCheck,
    TemporalFieldDefinition,
    TemporalKind,
    TemporalReconciliationDefinition,
    TemporalReplicationRule,
    TimestampOrderingRule,
    get_dataset_definition,
)
from ql2_sixt_canada_analysis.streams import (
    CollectionScheduleAssessment,
    CollectionScheduleStatus,
    ScheduledCoverageBlocker,
    ScheduledCoverageReport,
    StreamTimeCoverage,
    assess_collection_schedule,
    assess_scheduled_time_coverage,
    ExpectedLocationStreamsReport,
    ExpectedStreamBlocker,
    ExpectedStreamResult,
    assess_expected_location_streams,
    StreamEventAccounting,
    LocationStreamError,
    LocationStreamInvestigationReport,
    LocationStreamStatus,
    PipelineStage,
    StreamContinuity,
    TimeCoverageStatus,
    investigate_location_stream,
    resolve_expected_location,
    validate_location_stream,
)
from ql2_sixt_canada_analysis.city_integrity import (
    CITY_INTEGRITY_SAMPLE_LIMIT,
    CityIntegrityBlocker,
    CityIntegrityError,
    CityIntegrityReport,
    ScopeMismatchSample,
    assess_city_integrity,
    unassignable_scope_mask,
    validate_city_integrity,
)
from ql2_sixt_canada_analysis.join_readiness import (
    JobDetailJoinBlocker,
    JobDetailJoinReadiness,
    UntrustedJoinError,
    assess_job_detail_join_readiness,
    require_trusted_job_detail_join,
)
from ql2_sixt_canada_analysis.readiness import (
    CompletenessBlocker,
    CompletenessReport,
    assess_completeness,
    AnalyticalLocationKeys,
    LocationPolicyReport,
    PricingBlocker,
    PricingNotReadyError,
    PricingReadinessReport,
    apply_location_policy,
    assess_location_policy,
    assess_pricing_readiness,
    validate_pricing_readiness,
)
from ql2_sixt_canada_analysis.stability import (
    VehicleAttributeStabilityError,
    VehicleAttributeStabilityReport,
    VehicleStabilityPreconditionError,
    VehicleStabilityReport,
    VehicleEntityHistory,
    VehicleStabilityStatus,
    assess_vehicle_attribute_stability,
    classify_vehicle_entities,
    validate_vehicle_attribute_stability,
)
from ql2_sixt_canada_analysis.temporal import (
    RuleStatus,
    TemporalFieldReport,
    TemporalParseError,
    TemporalParseResult,
    TemporalPreconditionError,
    TemporalReconciliationError,
    TemporalReconciliationReport,
    TemporalRuleReport,
    DerivedReportingDays,
    DerivedTimestamps,
    ScrapeDateStatus,
    assess_temporal_reconciliation,
    canonical_utc_text,
    derive_reporting_days,
    derive_utc_timestamps,
    parse_temporal_field,
    validate_temporal_reconciliation,
)
from ql2_sixt_canada_analysis.unique_keys import (
    RawDatasetUniqueKeyReports,
    UniqueKeyReport,
    UniqueKeyViolationError,
    assess_raw_dataset_unique_keys,
    assess_unique_key,
    validate_raw_dataset_unique_keys,
    validate_unique_key,
)

__all__ = [
    "ANALYSIS_CARS_DEFINITION",
    "ANALYSIS_DATASET_DEFINITIONS",
    "ANALYSIS_JOBS_DEFINITION",
    "ANALYSIS_JOB_DETAIL_RELATIONSHIP",
    "ANALYSIS_LOCATION_STREAM_COMPARISON",
    "ANALYSIS_TEMPORAL_RECONCILIATION",
    "CONFIDENTIAL_TECHNICAL_COLUMNS",
    "JOB_LINKAGE_KEY_COLUMN",
    "OFFER_POSITION_KEY_COLUMN",
    "OFFER_POSITION_KEY_DTYPE",
    "SOURCE_JOB_IDENTIFIER_COLUMN",
    "SOURCE_OFFER_POSITION_COLUMN",
    "JobLinkageBlocker",
    "JobLinkageNotReadyError",
    "JobLinkagePolicy",
    "JobLinkagePolicyError",
    "JobLinkagePolicyStatus",
    "JobLinkagePreconditionError",
    "JobLinkageReport",
    "JobLinkageResult",
    "assess_job_linkage",
    "job_linkage_policy_from_record",
    "load_job_linkage_policy",
    "require_job_linkage",
    "CollectionScheduleAssessment",
    "CollectionScheduleStatus",
    "ScheduledCoverageBlocker",
    "ScheduledCoverageReport",
    "StreamTimeCoverage",
    "assess_collection_schedule",
    "assess_scheduled_time_coverage",
    "INVALID_OFFER_SAMPLE_LIMIT",
    "BaselineEvidence",
    "InvalidOfferSample",
    "OfferDefect",
    "OfferSignature",
    "OfferStreamRole",
    "offer_signature",
    "CITY_INTEGRITY_SAMPLE_LIMIT",
    "CityIntegrityBlocker",
    "CityIntegrityError",
    "CityIntegrityReport",
    "ScopeMismatchSample",
    "assess_city_integrity",
    "unassignable_scope_mask",
    "validate_city_integrity",
    "ExpectedLocationStreamsReport",
    "ExpectedStreamBlocker",
    "ExpectedStreamResult",
    "assess_expected_location_streams",
    "SAFE_ON_BAD_LINES",
    "IncompleteSourceOptionError",
    "location_pair_evidence",
    "DeclaredCountFieldReport",
    "job_detail_count_results",
    "StreamEventAccounting",
    "CompletenessBlocker",
    "CompletenessReport",
    "assess_completeness",
    "DuplicateInferenceBlocker",
    "MINIMUM_DUPLICATE_PAIRED_CAPTURES",
    "VehicleEntityHistory",
    "classify_vehicle_entities",
    "JobDetailJoinBlocker",
    "JobDetailJoinReadiness",
    "UntrustedJoinError",
    "assess_job_detail_join_readiness",
    "require_trusted_job_detail_join",
    "VANCOUVER_LOCATION_POLICY",
    "LocationIdentityPolicy",
    "LocationPolicyAuthority",
    "LocationPolicyConfigurationError",
    "LocationPolicyScope",
    "LocationPolicyScopeDefect",
    "LocationPolicyState",
    "assess_location_policy_scope",
    "AnalyticalLocationKeys",
    "LocationPolicyReport",
    "PricingBlocker",
    "PricingNotReadyError",
    "PricingReadinessReport",
    "apply_location_policy",
    "assess_location_policy",
    "assess_pricing_readiness",
    "validate_pricing_readiness",
    "VEHICLE_ATTRIBUTE_STABILITY",
    "AttributeComparisonPolicy",
    "MissingValueStabilityPolicy",
    "VehicleAttributeDefinition",
    "VehicleStabilityConfigurationError",
    "VehicleStabilityDefinition",
    "VehicleAttributeStabilityError",
    "VehicleAttributeStabilityReport",
    "VehicleStabilityPreconditionError",
    "VehicleStabilityReport",
    "VehicleStabilityStatus",
    "assess_vehicle_attribute_stability",
    "validate_vehicle_attribute_stability",
    "COMPARED_LOCATION_STREAMS",
    "LOCATION_STREAM_COMPARISON",
    "CapturePairing",
    "LocationStreamComparisonDefinition",
    "ComparisonPreconditionError",
    "IdentityEvidence",
    "LocationAliasNotConfirmedError",
    "LocationStreamComparisonReport",
    "LocationStreamComparisonStatus",
    "OfferSetResult",
    "ScopeBaseline",
    "TemporalOverlap",
    "canonical_location_keys",
    "compare_location_streams",
    "validate_confirmed_location_alias",
    "COLLECTION_SCHEDULE",
    "ReportingDateRule",
    "RuleStatus",
    "TEMPORAL_RECONCILIATION",
    "TemporalAwareness",
    "TemporalConfigurationError",
    "TemporalDateCheck",
    "TemporalFieldDefinition",
    "TemporalFieldReport",
    "TemporalKind",
    "TemporalParseError",
    "TemporalParseResult",
    "TemporalPreconditionError",
    "TemporalReconciliationDefinition",
    "TemporalReconciliationError",
    "TemporalReconciliationReport",
    "TemporalReplicationRule",
    "TemporalRuleReport",
    "TimestampOrderingRule",
    "assess_temporal_reconciliation",
    "parse_temporal_field",
    "validate_temporal_reconciliation",
    "DerivedTimestamps",
    "canonical_utc_text",
    "derive_utc_timestamps",
    "DerivedReportingDays",
    "ScrapeDateStatus",
    "derive_reporting_days",
    "CollectionScheduleDefinition",
    "DATASET_DEFINITIONS",
    "INVESTIGATED_LOCATION_STREAM",
    "LocationStreamError",
    "LocationStreamInvestigationReport",
    "LocationStreamStatus",
    "PipelineStage",
    "StreamContinuity",
    "TimeCoverageStatus",
    "assess_dataset_location_coverage",
    "investigate_location_stream",
    "resolve_expected_location",
    "validate_location_stream",
    "BlankRowResult",
    "DatasetDefinition",
    "DatasetKey",
    "EXPECTED_LOCATION_COVERAGE",
    "IDENTIFIER_DTYPE",
    "IdentifierDtypeError",
    "IdentifierTypeConflictError",
    "JOB_DETAIL_RELATIONSHIP",
    "JobDetailReconciliationError",
    "JobDetailReconciliationReport",
    "JobDetailRelationshipDefinition",
    "KeyConfigurationError",
    "LocationCoverageConfigurationError",
    "LocationCoverageDefinition",
    "LocationCoverageError",
    "LocationCoverageMode",
    "LocationCoverageReport",
    "OneToManyJoinReport",
    "OneToManyRelationshipError",
    "MissingIdentifierColumnError",
    "SHARED_IDENTIFIER_COLUMNS",
    "RawDatasetBlankRowResults",
    "RawDatasetPaths",
    "ReconciliationPreconditionError",
    "RelationshipConfigurationError",
    "RelationshipPreconditionError",
    "RawDatasetUniqueKeyReports",
    "RawDatasets",
    "UniqueKeyReport",
    "UniqueKeyViolationError",
    "ValidatedJoinError",
    "ValidatedJoinResult",
    "assess_expected_location_coverage",
    "assess_job_detail_reconciliation",
    "assess_one_to_many_join",
    "assess_raw_dataset_unique_keys",
    "assess_unique_key",
    "cast_identifier_fields",
    "cast_identifiers_for_raw_datasets",
    "discover_raw_csvs",
    "get_dataset_definition",
    "PROJECT_DEFAULT",
    "SOURCE_STREAM_COVERAGE_TEMPLATE",
    "project_default",
    "EXPECTED_STREAM_DECISIONS",
    "ExpectedStreamAuthorityStatus",
    "ExpectedStreamContract",
    "ExpectedStreamContractBlocker",
    "current_expected_stream_contract",
    "expected_stream_contract_from_record",
    "resolve_expected_stream_contract",
    "load_current_decision_record",
    "LOCATION_DECISIONS",
    "ComparisonPair",
    "ComparisonPairDefect",
    "ComparisonPairSet",
    "LocationAuthorityBlocker",
    "LocationAuthorityReport",
    "LocationAuthorityStatus",
    "LocationRoleMap",
    "RoleMapDefect",
    "assess_location_authority",
    "comparison_pairs_from_record",
    "current_location_authority",
    "CityTimezoneMap",
    "ExceptionsModel",
    "JobAssignmentFailure",
    "PerStreamSchedule",
    "PerStreamScheduledCoverageReport",
    "ScheduleAuthorityStatus",
    "ScheduleConfigurationError",
    "ScheduleCoverageBlocker",
    "ScheduleExceptions",
    "ScheduleFailureKind",
    "ScheduledPeriod",
    "SharingMode",
    "StreamPeriodCoverage",
    "StreamSchedule",
    "StreamScheduleException",
    "assess_per_stream_scheduled_coverage",
    "current_per_stream_schedule",
    "format_utc_instant",
    "materialize_local_hours",
    "normalize_finished_at",
    "schedule_from_record",
    "TemporalAuthority",
    "TemporalAuthorityBlocker",
    "TemporalDecisionStatus",
    "current_temporal_authority",
    "current_temporal_reconciliation",
    "RentalDatePolicy",
    "RentalDateReport",
    "RentalDateBlocker",
    "RentalPolicyStatus",
    "PeriodStatus",
    "AgreementStatus",
    "DateValueStatus",
    "DerivedRentalPeriods",
    "analysis_duration_cohort",
    "assess_rental_dates",
    "current_rental_date_policy",
    "derive_rental_periods",
    "parse_iso_dates",
    "rental_date_policy_from_record",
    "temporal_authority_from_record",
    "CapturePeriodIndex",
    "CaptureExclusionSet",
    "DetailEligibility",
    "FrameBinding",
    "PricingPopulation",
    "PricingPopulationError",
    "build_pricing_population",
    "frame_binding",
    "CanonicalOfferBlocker",
    "CanonicalOfferPolicy",
    "CanonicalOfferReport",
    "CanonicalOfferStatus",
    "UnassessableOfferReason",
    "assess_canonical_offers",
    "canonical_offer_policy_from_record",
    "current_canonical_offer_policy",
    "PricingPipelineResult",
    "BOUND_PIPELINE_REPORTS",
    "PipelineEvidenceManifest",
    "bind_pipeline_evidence",
    "pipeline_evidence_bound",
    "run_pricing_pipeline",
    "MATCH_IDENTITY_COLUMNS",
    "MIN_PAIRS_PER_TESTED_VEHICLE_TYPE",
    "MIN_PRODUCTS_PER_TESTED_VEHICLE_TYPE",
    "OVERALL",
    "PAIR_KEY_COLUMNS",
    "PAIR_COLUMNS",
    "CityMatchSummary",
    "DistributionSummary",
    "MatchCounts",
    "MatchOutcome",
    "MatchedLocationPricingBlocker",
    "MatchedLocationPricingError",
    "MatchedLocationPricingReport",
    "MatchedLocationPricingResult",
    "MatchedLocationPricingStatus",
    "PremiumMetric",
    "SignCounts",
    "ComparisonUnit",
    "VehicleTypeSummary",
    "VehicleTypeTest",
    "VehicleTypeTestStatus",
    "assess_matched_location_pricing",
    "city_summary_frame",
    "compare_vehicle_types",
    "holm_adjust",
    "match_count_frame",
    "plot_matched_location_premiums",
    "render_matched_location_pricing_markdown",
    "run_matched_location_pricing",
    "vehicle_type_summary_frame",
    "vehicle_type_test_frame",
    "write_matched_location_pricing_deliverables",
    "CANDIDATE_COLUMNS",
    "CAPTURE_STEP",
    "EVENT_IDENTITY_COLUMNS",
    "EVENT_INTERVAL_COLUMNS",
    "EVENT_KEY_COLUMNS",
    "EVENT_TIMESTAMP_COLUMN",
    "EVENT_UNIT_COLUMNS",
    "FORBIDDEN_TIMESTAMP_SOURCES",
    "SCHEDULED_PERIOD_FORMAT",
    "CaptureEvidenceError",
    "CaptureInterval",
    "CaptureState",
    "IntervalBreak",
    "LocationCaptureTimeline",
    "LocationPriceChangeSummary",
    "OutcomeCounts",
    "PriceChangeBlocker",
    "PriceChangeCandidateReport",
    "PriceChangeCandidateResult",
    "PriceChangeContractError",
    "PriceChangeStatus",
    "ScheduledCapture",
    "TerminalOutcome",
    "assess_price_change_candidates",
    "capture_timelines",
    "classify_endpoint_offers",
    "classify_price_change_candidates",
    "parse_scheduled_period",
    "price_change_candidates_from_pipeline",
    "price_change_cents",
    "validate_candidate_frame",
    "UnknownCanonicalLocationError",
    "approved_canonical_locations",
    "change_percent",
    "run_price_change_events",
    "CROSS_LOCATION_COLUMNS",
    "CROSS_LOCATION_PRODUCT_COLUMNS",
    "EVENT_TABLE_COLUMNS",
    "PERSISTENCE_COLUMNS",
    "CrossLocationOutcome",
    "CrossLocationStatus",
    "CrossLocationSummary",
    "FinalDecreaseCase",
    "FinalDecreaseIndicator",
    "FinalDecreaseStatus",
    "IntervalFlag",
    "LocationAnalysisSummary",
    "MovementClass",
    "NotTestableReason",
    "PersistenceOutcome",
    "PersistenceSummary",
    "PriceChangeAnalysisBlocker",
    "PriceChangeAnalysisReport",
    "PriceChangeAnalysisResult",
    "PriceChangeAnalysisStatus",
    "PriceChangeReconciliationError",
    "analyze_price_change_events",
    "event_heatmap_source",
    "exact_change_percent",
    "plot_price_change_heatmap",
    "price_change_analysis_from_pipeline",
    "run_price_change_analysis",
    "write_price_change_analysis_outputs",
    "DETAILED_EVENT_TABLE_COLUMNS",
    "DETAILED_EVENT_TABLE_FILENAME",
    "FORBIDDEN_SANITIZED_COLUMNS",
    "HEATMAP_FILENAME",
    "HEATMAP_SOURCE_COLUMNS",
    "MANIFEST_FILENAME",
    "MATERIAL_SELECTION_RULE",
    "SANITIZED_COLUMN_ALLOWLIST",
    "SANITIZED_TABLE_SCHEMAS",
    "InterpretationStatus",
    "PresentationTables",
    "PriceChangePresentationBlocker",
    "PriceChangePresentationReport",
    "PriceChangePresentationResult",
    "PriceChangePresentationStatus",
    "PrivacyViolationError",
    "build_detailed_event_table",
    "build_presentation_tables",
    "export_sanitized_tables",
    "heatmap_source_frame",
    "presentation_from_pipeline",
    "render_price_change_heatmap",
    "run_price_change_presentation",
    "validate_sanitized_frame",
    "write_detailed_event_table",
    "write_presentation_manifest",
    "ASSORTMENT_BREAK_REASONS",
    "ASSORTMENT_TIMELINE_COLUMNS",
    "DEFAULT_ASSORTMENT_DEFINITION",
    "DEFAULT_UNUSUAL_DROP_POLICY",
    "AnomalyPolicyStatus",
    "AnomalyPolicyUnavailableError",
    "AssessabilityStatus",
    "AssortmentBlocker",
    "AssortmentComparison",
    "AssortmentContractError",
    "AssortmentInterpretation",
    "DefinitionStatus",
    "DenominatorStatus",
    "UnusualDropPolicy",
    "VisibleAssortmentDefinition",
    "assortment_evidence_blockers",
    "classify_unusual_drop",
    "compare_assortment",
    "distinct_product_count",
    "MEMBERSHIP_COLUMNS",
    "RENTAL_CONTEXT_CHANGED",
    "AssortmentCaptureError",
    "AssortmentCounts",
    "AssortmentIdentityError",
    "AssortmentLocationError",
    "AssortmentPriceEvidenceError",
    "AssortmentReconciliationError",
    "AssortmentReport",
    "AssortmentStatus",
    "LocationAssortmentSummary",
    "ProductMembership",
    "RentalContextError",
    "VisibleAssortmentResult",
    "assess_visible_assortment",
    "calculate_visible_assortment",
    "run_visible_assortment",
    "validate_assortment_timeline",
    "validate_price_coincidence",
    "visible_assortment_from_pipeline",
    "ASSORTMENT_COLUMN_ALLOWLIST",
    "ASSORTMENT_COLUMN_KINDS",
    "ASSORTMENT_RECONCILIATION_CHECKS",
    "ASSORTMENT_TABLE_SCHEMAS",
    "FORBIDDEN_ASSORTMENT_COLUMNS",
    "NARRATIVE_SECTIONS",
    "TIMELINE_SOURCE_COLUMNS",
    "AssortmentNarrative",
    "AssortmentPresentationBlocker",
    "AssortmentPresentationReport",
    "AssortmentPresentationResult",
    "AssortmentPresentationStatus",
    "AssortmentPresentationTables",
    "AssortmentPrivacyError",
    "DropPattern",
    "ReviewStatus",
    "Simultaneity",
    "assortment_persistence_approved",
    "assortment_presentation_from_pipeline",
    "assortment_timeline_png",
    "assortment_timeline_source_frame",
    "build_assortment_narrative",
    "build_assortment_presentation_tables",
    "run_assortment_presentation",
    "validate_assortment_table",
    "DATA_PLAN_RECONCILIATION",
    "DEFAULT_SYNCHRONIZED_MOVEMENT_POLICY",
    "MONITORING_CONTROLS",
    "MONITORING_TABLE_COLUMNS",
    "PRODUCTION_CALIBRATION_REQUIREMENTS",
    "SEVERITY_DESCRIPTIONS",
    "STATUS_DESCRIPTIONS",
    "CalibrationStatus",
    "ControlEvaluation",
    "ControlStatus",
    "EvidenceGap",
    "MonitoringBlocker",
    "MonitoringControl",
    "MonitoringControlId",
    "MonitoringContractError",
    "MonitoringEvidence",
    "MonitoringFinding",
    "MonitoringNote",
    "MonitoringReport",
    "MonitoringReportStatus",
    "MonitoringResult",
    "Severity",
    "SynchronizedMovementPolicy",
    "blocked_monitoring_report",
    "evaluate_monitoring_controls",
    "monitoring_control",
    "monitoring_control_table",
    "monitoring_evidence_from_pipeline",
    "monitoring_from_pipeline",
    "monitoring_summary_lines",
    "run_monitoring",
    "severity_scale_table",
    "status_legend_table",
    "validate_monitoring_table",
    "final_case_table",
    "magnitude_suppressed",
    "magnitude_disclosable",
    "MINIMUM_MAGNITUDE_CONTRIBUTORS",
    "SANITIZED_COLUMN_KINDS",
    "RECONCILIATION_CHECKS",
    "presentation_settings",
    "heatmap_png",
    "PRESENTATION_OUTPUT_DIR_ENV_VAR",
    "DETAIL_EXPORT_ENV_VAR",
    "location_authority_from_record",
    "role_map_from_record",
    "vancouver_policy_from_record",
    "join_jobs_to_details",
    "load_raw_datasets",
    "remove_blank_rows_from_raw_datasets",
    "remove_completely_blank_rows",
    "validate_identifier_dtypes",
    "validate_expected_location_coverage",
    "validate_job_detail_reconciliation",
    "validate_one_to_many_join",
    "validate_raw_dataset_identifier_dtypes",
    "validate_raw_dataset_unique_keys",
    "validate_unique_key",
]


#: Names served lazily from :mod:`ql2_sixt_canada_analysis.job_linkage`, which
#: depends on the authority-record module; loading it on first use keeps
#: ``python -m ql2_sixt_canada_analysis.authority_decisions`` free of a re-import.
_LAZY_JOB_LINKAGE = frozenset({
    "JobLinkageBlocker",
    "JobLinkageNotReadyError",
    "JobLinkagePolicy",
    "JobLinkagePolicyError",
    "JobLinkagePolicyStatus",
    "JobLinkagePreconditionError",
    "JobLinkageReport",
    "JobLinkageResult",
    "assess_job_linkage",
    "job_linkage_policy_from_record",
    "load_job_linkage_policy",
    "require_job_linkage",
})


#: The authority-resolved contract and the definitions built on it (resolved
#: on first access from :mod:`ql2_sixt_canada_analysis.schemas`).
_LAZY_SCHEMAS = frozenset({"ANALYSIS_LOCATION_STREAM_COMPARISON", "EXPECTED_LOCATION_COVERAGE",
                           "LOCATION_STREAM_COMPARISON", "VANCOUVER_LOCATION_POLICY"})

#: Names served lazily from :mod:`ql2_sixt_canada_analysis.expected_stream_contract`
#: and :mod:`ql2_sixt_canada_analysis.authority_decisions`.
_LAZY_OTHER = {
    "EXPECTED_STREAM_DECISIONS": "expected_stream_contract",
    "ExpectedStreamAuthorityStatus": "expected_stream_contract",
    "ExpectedStreamContract": "expected_stream_contract",
    "ExpectedStreamContractBlocker": "expected_stream_contract",
    "current_expected_stream_contract": "expected_stream_contract",
    "expected_stream_contract_from_record": "expected_stream_contract",
    "resolve_expected_stream_contract": "expected_stream_contract",
    "load_current_decision_record": "authority_decisions",
    "LOCATION_DECISIONS": "location_authority",
    "ComparisonPair": "location_authority",
    "ComparisonPairDefect": "location_authority",
    "ComparisonPairSet": "location_authority",
    "LocationAuthorityBlocker": "location_authority",
    "LocationAuthorityReport": "location_authority",
    "LocationAuthorityStatus": "location_authority",
    "LocationRoleMap": "location_authority",
    "RoleMapDefect": "location_authority",
    "assess_location_authority": "location_authority",
    "comparison_pairs_from_record": "location_authority",
    "current_location_authority": "location_authority",
    "location_authority_from_record": "location_authority",
    "role_map_from_record": "location_authority",
    "vancouver_policy_from_record": "location_authority",
    "CityTimezoneMap": "collection_schedule",
    "ExceptionsModel": "collection_schedule",
    "JobAssignmentFailure": "collection_schedule",
    "PerStreamSchedule": "collection_schedule",
    "PerStreamScheduledCoverageReport": "collection_schedule",
    "ScheduleAuthorityStatus": "collection_schedule",
    "ScheduleConfigurationError": "collection_schedule",
    "ScheduleCoverageBlocker": "collection_schedule",
    "ScheduleExceptions": "collection_schedule",
    "ScheduleFailureKind": "collection_schedule",
    "ScheduledPeriod": "collection_schedule",
    "SharingMode": "collection_schedule",
    "StreamPeriodCoverage": "collection_schedule",
    "StreamSchedule": "collection_schedule",
    "StreamScheduleException": "collection_schedule",
    "assess_per_stream_scheduled_coverage": "collection_schedule",
    "current_per_stream_schedule": "collection_schedule",
    "format_utc_instant": "collection_schedule",
    "materialize_local_hours": "collection_schedule",
    "normalize_finished_at": "collection_schedule",
    "schedule_from_record": "collection_schedule",
    "TemporalAuthority": "temporal_authority",
    "TemporalAuthorityBlocker": "temporal_authority",
    "TemporalDecisionStatus": "temporal_authority",
    "current_temporal_authority": "temporal_authority",
    "current_temporal_reconciliation": "temporal_authority",
    "RentalDatePolicy": "rental_dates",
    "RentalDateReport": "rental_dates",
    "RentalDateBlocker": "rental_dates",
    "RentalPolicyStatus": "rental_dates",
    "PeriodStatus": "rental_dates",
    "AgreementStatus": "rental_dates",
    "DateValueStatus": "rental_dates",
    "DerivedRentalPeriods": "rental_dates",
    "analysis_duration_cohort": "rental_dates",
    "assess_rental_dates": "rental_dates",
    "current_rental_date_policy": "rental_dates",
    "derive_rental_periods": "rental_dates",
    "parse_iso_dates": "rental_dates",
    "rental_date_policy_from_record": "rental_dates",
    "temporal_authority_from_record": "temporal_authority",
    "CapturePeriodIndex": "collection_schedule",
    "CaptureExclusionSet": "collection_schedule",
    "DetailEligibility": "pricing_population",
    "FrameBinding": "pricing_population",
    "PricingPopulation": "pricing_population",
    "PricingPopulationError": "pricing_population",
    "build_pricing_population": "pricing_population",
    "frame_binding": "pricing_population",
    "CanonicalOfferBlocker": "canonical_offers",
    "CanonicalOfferPolicy": "canonical_offers",
    "CanonicalOfferReport": "canonical_offers",
    "CanonicalOfferStatus": "canonical_offers",
    "UnassessableOfferReason": "canonical_offers",
    "assess_canonical_offers": "canonical_offers",
    "canonical_offer_policy_from_record": "canonical_offers",
    "current_canonical_offer_policy": "canonical_offers",
    "PricingPipelineResult": "pricing_pipeline",
    "BOUND_PIPELINE_REPORTS": "pricing_pipeline",
    "PipelineEvidenceManifest": "pricing_pipeline",
    "bind_pipeline_evidence": "pricing_pipeline",
    "pipeline_evidence_bound": "pricing_pipeline",
    "run_pricing_pipeline": "pricing_pipeline",
    "MATCH_IDENTITY_COLUMNS": "matched_location_pricing",
    "MIN_PAIRS_PER_TESTED_VEHICLE_TYPE": "matched_location_pricing",
    "MIN_PRODUCTS_PER_TESTED_VEHICLE_TYPE": "matched_location_pricing",
    "OVERALL": "matched_location_pricing",
    "PAIR_KEY_COLUMNS": "matched_location_pricing",
    "PAIR_COLUMNS": "matched_location_pricing",
    "CityMatchSummary": "matched_location_pricing",
    "DistributionSummary": "matched_location_pricing",
    "MatchCounts": "matched_location_pricing",
    "MatchOutcome": "matched_location_pricing",
    "MatchedLocationPricingBlocker": "matched_location_pricing",
    "MatchedLocationPricingError": "matched_location_pricing",
    "MatchedLocationPricingReport": "matched_location_pricing",
    "MatchedLocationPricingResult": "matched_location_pricing",
    "MatchedLocationPricingStatus": "matched_location_pricing",
    "PremiumMetric": "matched_location_pricing",
    "SignCounts": "matched_location_pricing",
    "ComparisonUnit": "matched_location_pricing",
    "VehicleTypeSummary": "matched_location_pricing",
    "VehicleTypeTest": "matched_location_pricing",
    "VehicleTypeTestStatus": "matched_location_pricing",
    "assess_matched_location_pricing": "matched_location_pricing",
    "city_summary_frame": "matched_location_pricing",
    "compare_vehicle_types": "matched_location_pricing",
    "holm_adjust": "matched_location_pricing",
    "match_count_frame": "matched_location_pricing",
    "plot_matched_location_premiums": "matched_location_pricing",
    "render_matched_location_pricing_markdown": "matched_location_pricing",
    "run_matched_location_pricing": "matched_location_pricing",
    "vehicle_type_summary_frame": "matched_location_pricing",
    "vehicle_type_test_frame": "matched_location_pricing",
    "write_matched_location_pricing_deliverables": "matched_location_pricing",
    "CANDIDATE_COLUMNS": "price_change_events",
    "CAPTURE_STEP": "price_change_events",
    "EVENT_IDENTITY_COLUMNS": "price_change_events",
    "EVENT_INTERVAL_COLUMNS": "price_change_events",
    "EVENT_KEY_COLUMNS": "price_change_events",
    "EVENT_TIMESTAMP_COLUMN": "price_change_events",
    "EVENT_UNIT_COLUMNS": "price_change_events",
    "FORBIDDEN_TIMESTAMP_SOURCES": "price_change_events",
    "SCHEDULED_PERIOD_FORMAT": "price_change_events",
    "CaptureEvidenceError": "price_change_events",
    "CaptureInterval": "price_change_events",
    "CaptureState": "price_change_events",
    "IntervalBreak": "price_change_events",
    "LocationCaptureTimeline": "price_change_events",
    "LocationPriceChangeSummary": "price_change_events",
    "OutcomeCounts": "price_change_events",
    "PriceChangeBlocker": "price_change_events",
    "PriceChangeCandidateReport": "price_change_events",
    "PriceChangeCandidateResult": "price_change_events",
    "PriceChangeContractError": "price_change_events",
    "PriceChangeStatus": "price_change_events",
    "ScheduledCapture": "price_change_events",
    "TerminalOutcome": "price_change_events",
    "assess_price_change_candidates": "price_change_events",
    "capture_timelines": "price_change_events",
    "classify_endpoint_offers": "price_change_events",
    "classify_price_change_candidates": "price_change_events",
    "parse_scheduled_period": "price_change_events",
    "price_change_candidates_from_pipeline": "price_change_events",
    "price_change_cents": "price_change_events",
    "validate_candidate_frame": "price_change_events",
    "UnknownCanonicalLocationError": "price_change_events",
    "approved_canonical_locations": "price_change_events",
    "change_percent": "price_change_events",
    "run_price_change_events": "price_change_events",
    "CROSS_LOCATION_COLUMNS": "price_change_analysis",
    "CROSS_LOCATION_PRODUCT_COLUMNS": "price_change_analysis",
    "EVENT_TABLE_COLUMNS": "price_change_analysis",
    "PERSISTENCE_COLUMNS": "price_change_analysis",
    "CrossLocationOutcome": "price_change_analysis",
    "CrossLocationStatus": "price_change_analysis",
    "CrossLocationSummary": "price_change_analysis",
    "FinalDecreaseCase": "price_change_analysis",
    "FinalDecreaseIndicator": "price_change_analysis",
    "FinalDecreaseStatus": "price_change_analysis",
    "IntervalFlag": "price_change_analysis",
    "LocationAnalysisSummary": "price_change_analysis",
    "MovementClass": "price_change_analysis",
    "NotTestableReason": "price_change_analysis",
    "PersistenceOutcome": "price_change_analysis",
    "PersistenceSummary": "price_change_analysis",
    "PriceChangeAnalysisBlocker": "price_change_analysis",
    "PriceChangeAnalysisReport": "price_change_analysis",
    "PriceChangeAnalysisResult": "price_change_analysis",
    "PriceChangeAnalysisStatus": "price_change_analysis",
    "PriceChangeReconciliationError": "price_change_analysis",
    "analyze_price_change_events": "price_change_analysis",
    "event_heatmap_source": "price_change_analysis",
    "exact_change_percent": "price_change_analysis",
    "plot_price_change_heatmap": "price_change_analysis",
    "price_change_analysis_from_pipeline": "price_change_analysis",
    "run_price_change_analysis": "price_change_analysis",
    "write_price_change_analysis_outputs": "price_change_analysis",
    "DETAILED_EVENT_TABLE_COLUMNS": "price_change_presentation",
    "DETAILED_EVENT_TABLE_FILENAME": "price_change_presentation",
    "FORBIDDEN_SANITIZED_COLUMNS": "price_change_presentation",
    "HEATMAP_FILENAME": "price_change_presentation",
    "HEATMAP_SOURCE_COLUMNS": "price_change_presentation",
    "MANIFEST_FILENAME": "price_change_presentation",
    "MATERIAL_SELECTION_RULE": "price_change_presentation",
    "SANITIZED_COLUMN_ALLOWLIST": "price_change_presentation",
    "SANITIZED_TABLE_SCHEMAS": "price_change_presentation",
    "InterpretationStatus": "price_change_presentation",
    "PresentationTables": "price_change_presentation",
    "PriceChangePresentationBlocker": "price_change_presentation",
    "PriceChangePresentationReport": "price_change_presentation",
    "PriceChangePresentationResult": "price_change_presentation",
    "PriceChangePresentationStatus": "price_change_presentation",
    "PrivacyViolationError": "price_change_presentation",
    "build_detailed_event_table": "price_change_presentation",
    "build_presentation_tables": "price_change_presentation",
    "export_sanitized_tables": "price_change_presentation",
    "heatmap_source_frame": "price_change_presentation",
    "presentation_from_pipeline": "price_change_presentation",
    "render_price_change_heatmap": "price_change_presentation",
    "run_price_change_presentation": "price_change_presentation",
    "validate_sanitized_frame": "price_change_presentation",
    "write_detailed_event_table": "price_change_presentation",
    "write_presentation_manifest": "price_change_presentation",
    "ASSORTMENT_BREAK_REASONS": "assortment_contract",
    "ASSORTMENT_TIMELINE_COLUMNS": "assortment_contract",
    "DEFAULT_ASSORTMENT_DEFINITION": "assortment_contract",
    "DEFAULT_UNUSUAL_DROP_POLICY": "assortment_contract",
    "AnomalyPolicyStatus": "assortment_contract",
    "AnomalyPolicyUnavailableError": "assortment_contract",
    "AssessabilityStatus": "assortment_contract",
    "AssortmentBlocker": "assortment_contract",
    "AssortmentComparison": "assortment_contract",
    "AssortmentContractError": "assortment_contract",
    "AssortmentInterpretation": "assortment_contract",
    "DefinitionStatus": "assortment_contract",
    "DenominatorStatus": "assortment_contract",
    "UnusualDropPolicy": "assortment_contract",
    "VisibleAssortmentDefinition": "assortment_contract",
    "assortment_evidence_blockers": "assortment_contract",
    "classify_unusual_drop": "assortment_contract",
    "compare_assortment": "assortment_contract",
    "distinct_product_count": "assortment_contract",
    "MEMBERSHIP_COLUMNS": "visible_assortment",
    "RENTAL_CONTEXT_CHANGED": "visible_assortment",
    "AssortmentCaptureError": "visible_assortment",
    "AssortmentCounts": "visible_assortment",
    "AssortmentIdentityError": "visible_assortment",
    "AssortmentLocationError": "visible_assortment",
    "AssortmentPriceEvidenceError": "visible_assortment",
    "AssortmentReconciliationError": "visible_assortment",
    "AssortmentReport": "visible_assortment",
    "AssortmentStatus": "visible_assortment",
    "LocationAssortmentSummary": "visible_assortment",
    "ProductMembership": "visible_assortment",
    "RentalContextError": "visible_assortment",
    "VisibleAssortmentResult": "visible_assortment",
    "assess_visible_assortment": "visible_assortment",
    "calculate_visible_assortment": "visible_assortment",
    "run_visible_assortment": "visible_assortment",
    "validate_assortment_timeline": "visible_assortment",
    "validate_price_coincidence": "visible_assortment",
    "visible_assortment_from_pipeline": "visible_assortment",
    "ASSORTMENT_COLUMN_ALLOWLIST": "assortment_presentation",
    "ASSORTMENT_COLUMN_KINDS": "assortment_presentation",
    "ASSORTMENT_RECONCILIATION_CHECKS": "assortment_presentation",
    "ASSORTMENT_TABLE_SCHEMAS": "assortment_presentation",
    "FORBIDDEN_ASSORTMENT_COLUMNS": "assortment_presentation",
    "NARRATIVE_SECTIONS": "assortment_presentation",
    "TIMELINE_SOURCE_COLUMNS": "assortment_presentation",
    "AssortmentNarrative": "assortment_presentation",
    "AssortmentPresentationBlocker": "assortment_presentation",
    "AssortmentPresentationReport": "assortment_presentation",
    "AssortmentPresentationResult": "assortment_presentation",
    "AssortmentPresentationStatus": "assortment_presentation",
    "AssortmentPresentationTables": "assortment_presentation",
    "AssortmentPrivacyError": "assortment_presentation",
    "DropPattern": "assortment_presentation",
    "ReviewStatus": "assortment_presentation",
    "Simultaneity": "assortment_presentation",
    "assortment_persistence_approved": "assortment_presentation",
    "assortment_presentation_from_pipeline": "assortment_presentation",
    "assortment_timeline_png": "assortment_presentation",
    "assortment_timeline_source_frame": "assortment_presentation",
    "build_assortment_narrative": "assortment_presentation",
    "build_assortment_presentation_tables": "assortment_presentation",
    "run_assortment_presentation": "assortment_presentation",
    "validate_assortment_table": "assortment_presentation",
    "DATA_PLAN_RECONCILIATION": "monitoring",
    "DEFAULT_SYNCHRONIZED_MOVEMENT_POLICY": "monitoring",
    "MONITORING_CONTROLS": "monitoring",
    "MONITORING_TABLE_COLUMNS": "monitoring",
    "PRODUCTION_CALIBRATION_REQUIREMENTS": "monitoring",
    "SEVERITY_DESCRIPTIONS": "monitoring",
    "STATUS_DESCRIPTIONS": "monitoring",
    "CalibrationStatus": "monitoring",
    "ControlEvaluation": "monitoring",
    "ControlStatus": "monitoring",
    "EvidenceGap": "monitoring",
    "MonitoringBlocker": "monitoring",
    "MonitoringControl": "monitoring",
    "MonitoringControlId": "monitoring",
    "MonitoringContractError": "monitoring",
    "MonitoringEvidence": "monitoring",
    "MonitoringFinding": "monitoring",
    "MonitoringNote": "monitoring",
    "MonitoringReport": "monitoring",
    "MonitoringReportStatus": "monitoring",
    "MonitoringResult": "monitoring",
    "Severity": "monitoring",
    "SynchronizedMovementPolicy": "monitoring",
    "blocked_monitoring_report": "monitoring",
    "evaluate_monitoring_controls": "monitoring",
    "monitoring_control": "monitoring",
    "monitoring_control_table": "monitoring",
    "monitoring_evidence_from_pipeline": "monitoring",
    "monitoring_from_pipeline": "monitoring",
    "monitoring_summary_lines": "monitoring",
    "run_monitoring": "monitoring",
    "severity_scale_table": "monitoring",
    "status_legend_table": "monitoring",
    "validate_monitoring_table": "monitoring",
    "final_case_table": "price_change_presentation",
    "magnitude_suppressed": "price_change_presentation",
    "magnitude_disclosable": "price_change_presentation",
    "MINIMUM_MAGNITUDE_CONTRIBUTORS": "price_change_presentation",
    "SANITIZED_COLUMN_KINDS": "price_change_presentation",
    "RECONCILIATION_CHECKS": "price_change_presentation",
    "presentation_settings": "price_change_presentation",
    "heatmap_png": "price_change_presentation",
    "PRESENTATION_OUTPUT_DIR_ENV_VAR": "price_change_presentation",
    "DETAIL_EXPORT_ENV_VAR": "price_change_presentation",
}


def __getattr__(name: str):  # type: ignore[no-untyped-def]  # PEP 562
    if name in _LAZY_SCHEMAS:
        from ql2_sixt_canada_analysis import schemas

        return getattr(schemas, name)
    if name in _LAZY_OTHER:
        import importlib

        return getattr(importlib.import_module(f"ql2_sixt_canada_analysis.{_LAZY_OTHER[name]}"), name)
    if name in _LAZY_JOB_LINKAGE:
        from ql2_sixt_canada_analysis import job_linkage

        return getattr(job_linkage, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
